import { Event, Team, Submission } from '@/contexts/EventContext';

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'AI Innovation Hackathon 2025',
    description: 'Build the next generation of AI-powered applications that solve real-world problems. Focus on machine learning, natural language processing, or computer vision.',
    organizerId: 'org1',
    organizer: 'TechCorp Innovation Lab',
    category: 'hackathon',
    status: 'upcoming',
    registrationStart: '2025-08-20T00:00:00Z',
    registrationEnd: '2025-09-15T23:59:59Z',
    eventStart: '2025-09-20T09:00:00Z',
    eventEnd: '2025-09-22T18:00:00Z',
    maxTeamSize: 4,
    minTeamSize: 1,
    prizes: ['$10,000 First Prize', '$5,000 Second Prize', '$2,500 Third Prize', 'Mentorship Opportunities'],
    rules: [
      'Teams can have 1-4 members',
      'Code must be written during the event',
      'Use of existing libraries is allowed',
      'All submissions must include source code and demo',
      'Projects must be original work',
    ],
    requirements: [
      'Basic programming knowledge',
      'Laptop with development environment',
      'Git/GitHub account',
      'Presentation slides for final demo',
    ],
    submissionDeadline: '2025-09-22T16:00:00Z',
    image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&h=400&fit=crop',
    registrationCount: 247,
    maxRegistrations: 500,
    tags: ['AI', 'Machine Learning', 'Innovation', 'Technology'],
    difficulty: 'intermediate',
  },
  {
    id: '2',
    title: 'Web3 DeFi Challenge',
    description: 'Create innovative decentralized finance applications using blockchain technology. Build the future of finance with smart contracts and DApps.',
    organizerId: 'org2',
    organizer: 'Blockchain Association',
    category: 'hackathon',
    status: 'ongoing',
    registrationStart: '2025-08-01T00:00:00Z',
    registrationEnd: '2025-08-15T23:59:59Z',
    eventStart: '2025-08-16T09:00:00Z',
    eventEnd: '2025-08-19T18:00:00Z',
    maxTeamSize: 3,
    minTeamSize: 1,
    prizes: ['$15,000 First Prize', '$8,000 Second Prize', '$3,000 Third Prize', 'Crypto Tokens'],
    rules: [
      'Teams can have 1-3 members',
      'Must use blockchain technology',
      'Smart contracts must be deployed on testnet',
      'Include comprehensive documentation',
      'Demo must show working DApp',
    ],
    requirements: [
      'Solidity programming experience',
      'Understanding of blockchain concepts',
      'Web3 development tools',
      'Metamask wallet',
    ],
    submissionDeadline: '2025-08-19T15:00:00Z',
    image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&h=400&fit=crop',
    registrationCount: 156,
    maxRegistrations: 300,
    tags: ['Web3', 'Blockchain', 'DeFi', 'Smart Contracts'],
    difficulty: 'advanced',
  },
  {
    id: '3',
    title: 'Mobile App Development Sprint',
    description: 'Design and develop innovative mobile applications for iOS and Android. Focus on user experience, performance, and solving everyday problems.',
    organizerId: 'org3',
    organizer: 'Mobile Developers Guild',
    category: 'competition',
    status: 'upcoming',
    registrationStart: '2025-09-01T00:00:00Z',
    registrationEnd: '2025-09-25T23:59:59Z',
    eventStart: '2025-10-01T09:00:00Z',
    eventEnd: '2025-10-03T18:00:00Z',
    maxTeamSize: 5,
    minTeamSize: 2,
    prizes: ['$8,000 First Prize', '$4,000 Second Prize', '$2,000 Third Prize', 'App Store Credits'],
    rules: [
      'Teams must have 2-5 members',
      'Cross-platform development encouraged',
      'App must be functional on real devices',
      'Include app store listing materials',
      'User testing required',
    ],
    requirements: [
      'Mobile development experience',
      'iOS/Android devices for testing',
      'Development environment setup',
      'App store developer accounts',
    ],
    submissionDeadline: '2025-10-03T16:00:00Z',
    image: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=400&fit=crop',
    registrationCount: 89,
    maxRegistrations: 200,
    tags: ['Mobile', 'iOS', 'Android', 'UX/UI'],
    difficulty: 'intermediate',
  },
  {
    id: '4',
    title: 'Sustainability Tech Workshop',
    description: 'Learn and build technology solutions for environmental challenges. Focus on clean tech, renewable energy, and sustainable development.',
    organizerId: 'org4',
    organizer: 'Green Tech Initiative',
    category: 'workshop',
    status: 'upcoming',
    registrationStart: '2025-08-25T00:00:00Z',
    registrationEnd: '2025-09-10T23:59:59Z',
    eventStart: '2025-09-15T10:00:00Z',
    eventEnd: '2025-09-15T17:00:00Z',
    maxTeamSize: 1,
    minTeamSize: 1,
    prizes: ['Certificates', 'Networking Opportunities', 'Learning Resources'],
    rules: [
      'Individual participation only',
      'Hands-on learning experience',
      'Completion of all modules required',
      'Final project presentation',
    ],
    requirements: [
      'Interest in sustainability',
      'Basic programming knowledge helpful',
      'Laptop required',
      'Notebook for taking notes',
    ],
    submissionDeadline: '2025-09-15T16:00:00Z',
    image: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&h=400&fit=crop',
    registrationCount: 45,
    maxRegistrations: 100,
    tags: ['Sustainability', 'Clean Tech', 'Environment', 'Learning'],
    difficulty: 'beginner',
  },
  {
    id: '5',
    title: 'Cybersecurity CTF Championship',
    description: 'Capture The Flag competition focusing on various cybersecurity challenges including web security, cryptography, and network security.',
    organizerId: 'org5',
    organizer: 'CyberSec Community',
    category: 'competition',
    status: 'upcoming',
    registrationStart: '2025-09-10T00:00:00Z',
    registrationEnd: '2025-10-05T23:59:59Z',
    eventStart: '2025-10-10T09:00:00Z',
    eventEnd: '2025-10-12T18:00:00Z',
    maxTeamSize: 4,
    minTeamSize: 1,
    prizes: ['$12,000 First Prize', '$6,000 Second Prize', '$3,000 Third Prize', 'Security Tools License'],
    rules: [
      'Teams can have 1-4 members',
      'Multiple challenge categories',
      'No external help allowed during competition',
      'Must document solution approaches',
      'Real-time leaderboard tracking',
    ],
    requirements: [
      'Cybersecurity knowledge',
      'Linux command line skills',
      'Network analysis tools',
      'Programming skills in multiple languages',
    ],
    submissionDeadline: '2025-10-12T17:00:00Z',
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&h=400&fit=crop',
    registrationCount: 178,
    maxRegistrations: 400,
    tags: ['Cybersecurity', 'CTF', 'Hacking', 'Network Security'],
    difficulty: 'advanced',
  },
  {
    id: '6',
    title: 'Data Science Analytics Challenge',
    description: 'Analyze complex datasets to derive meaningful insights and build predictive models. Work with real-world data from industry partners.',
    organizerId: 'org6',
    organizer: 'Data Science Institute',
    category: 'competition',
    status: 'completed',
    registrationStart: '2025-07-01T00:00:00Z',
    registrationEnd: '2025-07-20T23:59:59Z',
    eventStart: '2025-07-25T09:00:00Z',
    eventEnd: '2025-07-28T18:00:00Z',
    maxTeamSize: 3,
    minTeamSize: 1,
    prizes: ['$7,000 First Prize', '$3,500 Second Prize', '$1,500 Third Prize', 'Data Science Tools'],
    rules: [
      'Teams can have 1-3 members',
      'Use provided datasets only',
      'Include detailed analysis report',
      'Present findings to industry judges',
      'Code must be well-documented',
    ],
    requirements: [
      'Python or R programming',
      'Statistics and data analysis skills',
      'Data visualization tools',
      'Jupyter Notebook or similar',
    ],
    submissionDeadline: '2025-07-28T15:00:00Z',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=400&fit=crop',
    registrationCount: 134,
    maxRegistrations: 250,
    tags: ['Data Science', 'Analytics', 'Machine Learning', 'Python'],
    difficulty: 'intermediate',
  }
];

export const mockTeams: Team[] = [
  {
    id: 'team1',
    name: 'AI Innovators',
    eventId: '1',
    leaderId: '1',
    members: ['1', '2', '3'],
    submission: {
      id: 'sub1',
      title: 'Smart City Traffic Optimizer',
      description: 'AI-powered traffic management system using computer vision and machine learning',
      githubUrl: 'https://github.com/ai-innovators/traffic-optimizer',
      liveUrl: 'https://traffic-optimizer-demo.vercel.app',
      videoUrl: 'https://youtube.com/watch?v=demo1',
      submittedAt: '2025-08-18T14:30:00Z',
    },
  },
  {
    id: 'team2',
    name: 'DeFi Builders',
    eventId: '2',
    leaderId: '4',
    members: ['4', '5'],
    submission: {
      id: 'sub2',
      title: 'Decentralized Lending Protocol',
      description: 'Cross-chain lending platform with automated risk assessment',
      githubUrl: 'https://github.com/defi-builders/lending-protocol',
      liveUrl: 'https://defi-lending-demo.netlify.app',
      submittedAt: '2025-08-18T16:45:00Z',
    },
  },
];

export const mockSubmissions: Submission[] = [
  {
    id: 'sub1',
    eventId: '1',
    teamId: 'team1',
    teamName: 'AI Innovators',
    title: 'Smart City Traffic Optimizer',
    description: 'AI-powered traffic management system that uses computer vision to analyze traffic patterns and optimize signal timing in real-time. Reduces congestion by 35% in simulated environments.',
    githubUrl: 'https://github.com/ai-innovators/traffic-optimizer',
    liveUrl: 'https://traffic-optimizer-demo.vercel.app',
    videoUrl: 'https://youtube.com/watch?v=demo1',
    submittedAt: '2025-08-18T14:30:00Z',
    scores: [
      {
        judgeId: 'judge1',
        judgeName: 'Dr. Sarah Chen',
        innovation: 9,
        technical: 8,
        presentation: 9,
        impact: 9,
        feedback: 'Excellent innovative approach to urban traffic management. Strong technical implementation with clear real-world impact potential.',
      },
      {
        judgeId: 'judge2',
        judgeName: 'Prof. Michael Rodriguez',
        innovation: 8,
        technical: 9,
        presentation: 8,
        impact: 8,
        feedback: 'Solid technical execution with well-structured codebase. Could benefit from more detailed performance metrics.',
      },
    ],
    totalScore: 85,
    rank: 1,
  },
  {
    id: 'sub2',
    eventId: '2',
    teamId: 'team2',
    teamName: 'DeFi Builders',
    title: 'Decentralized Lending Protocol',
    description: 'Cross-chain lending platform that enables users to lend and borrow assets across multiple blockchains with automated risk assessment and dynamic interest rates.',
    githubUrl: 'https://github.com/defi-builders/lending-protocol',
    liveUrl: 'https://defi-lending-demo.netlify.app',
    submittedAt: '2025-08-18T16:45:00Z',
    scores: [
      {
        judgeId: 'judge3',
        judgeName: 'Alex Thompson',
        innovation: 9,
        technical: 9,
        presentation: 7,
        impact: 8,
        feedback: 'Innovative cross-chain solution with strong technical architecture. Presentation could be more polished.',
      },
    ],
    totalScore: 82.5,
    rank: 2,
  },
  {
    id: 'sub3',
    eventId: '6',
    teamId: 'team3',
    teamName: 'Data Wizards',
    title: 'Customer Churn Prediction Model',
    description: 'Advanced machine learning model that predicts customer churn with 94% accuracy using ensemble methods and feature engineering.',
    githubUrl: 'https://github.com/data-wizards/churn-prediction',
    submittedAt: '2025-07-28T13:20:00Z',
    scores: [
      {
        judgeId: 'judge4',
        judgeName: 'Dr. Emily Watson',
        innovation: 7,
        technical: 9,
        presentation: 8,
        impact: 8,
        feedback: 'Excellent technical implementation with impressive accuracy. Good practical business application.',
      },
    ],
    totalScore: 80,
    rank: 1,
  },
];

export const mockAnnouncements = [
  {
    id: '1',
    title: 'AI Innovation Hackathon Registration Open!',
    message: 'Early bird registration is now open for the AI Innovation Hackathon 2025. Register before September 1st for special perks!',
    timestamp: '2025-08-18T10:00:00Z',
    type: 'info' as const,
    eventId: '1',
  },
  {
    id: '2',
    title: 'Web3 DeFi Challenge - Final Day!',
    message: 'This is the final day of submissions for the Web3 DeFi Challenge. Make sure to submit your projects before 3 PM today!',
    timestamp: '2025-08-18T08:00:00Z',
    type: 'warning' as const,
    eventId: '2',
  },
  {
    id: '3',
    title: 'New Workshop Added: Sustainability Tech',
    message: 'We\'ve added a new workshop on Sustainability Tech. Learn how to build solutions for environmental challenges!',
    timestamp: '2025-08-17T15:30:00Z',
    type: 'success' as const,
    eventId: '4',
  },
  {
    id: '4',
    title: 'Judging Criteria Updated',
    message: 'We\'ve updated the judging criteria for all competitions. Please review the new guidelines in your event dashboard.',
    timestamp: '2025-08-17T09:15:00Z',
    type: 'info' as const,
  },
];
